# This is a basic workflow to help you get started with Actions
name: main

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: mkdir release
      - uses: maxheld83/pandoc@v2
        with:
          args: "--pdf-engine=xelatex --output=release/README.pdf README.md"
      - uses: actions/upload-artifact@master
        with:
          name: release
          path: release        
