# This is a basic workflow to help you get started with Actions

# 将修改后的README.md自动转换为pdf文件，保存在release中
name: md2pdf

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 创建release文件夹
      - name: mkdir release
        run: mkdir release

      # 使用pandoc进行转换
      - uses: docker://ghcr.io/44smkn/pandoc/ja:0.1.1
        with:
          args: README.md -s -o release/result.pdf --pdf-engine=wkhtmltopdf
    
      # 将创建的pdf文件上传
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release_pdf
          files: release/result.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
