# This is a basic workflow to help you get started with Actions

# 将修改后的README.md自动转换为pdf文件，保存在release中
name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - run: mkdir artifact
      - uses: maxheld83/pandoc@v2
        with:
          args: "--pdf-engine=xelatex --output=artifact/build.pdf README.md"
      - name: UploadArtifact
        uses: actions/upload-artifact@master
        with:
          name: build-${{ github.run_number }}
          path: artifact

      - name: PushCommit
        run: |
          cp artifact/build.pdf backups/${{ steps.date.outputs.date }}-build${{ github.run_number }}.pdf
          cp assets/REANDME.md backups/${{ steps.date.outputs.date }}-build${{ github.run_number }}.md
          git config user.name qifeng1128
          git config user.email 1419616173@qq.com
          git add .
          git commit -m "CI: produce ${{ steps.date.outputs.date }}-build${{ github.run_number }}.pdf"
          git push
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifact/build.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
